backend:
  name: git-gateway
  branch: netlify-identity # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads"
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "properties" # Used in routes, e.g., /admin/collections/blog
    label: "Properties" # Used in the UI
    folder: "_properties" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "properties"}
      - {label: "Property Address", name: "address", widget: "string"}
      - {label: "Leased?", name: "leased", widget: "boolean", default: false}
      - {label: "Furnished?", name: "furnished", widget: "boolean", default: false}
      - {label: "Available Date", name: "date", widget: "date"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Image 2", name: "image2", widget: "image"}
      - {label: "Image 3", name: "image3", widget: "image"}
      - {label: "Image 4", name: "image4", widget: "image"}
      - {label: "Image 5", name: "image5", widget: "image"}
      - {label: "Details", name: "body", widget: "markdown"}